interface BuildProjectFilesOptions {
  appId: string;
  appName: string;
  botUsername: string;
  /** When set, use `link:` protocol pointing to this local teleforge monorepo path. */
  linkPath?: string;
}

interface PackageNames {
  api: string;
  bot: string;
  types: string;
  web: string;
}

function teleforgeDependency(linkPath?: string): Record<string, string> {
  return {
    teleforge: !linkPath ? "^0.1.0" : `link:${linkPath}/packages/teleforge`
  };
}

export function buildProjectFiles(options: BuildProjectFilesOptions): Record<string, string> {
  const packageNames = getPackageNames(options.appId);

  return {
    ".env.example": envExample(),
    ".gitignore": generatedGitignore(),
    "README.md": generatedReadme(options),
    "package.json": generatedRootPackageJson(options),
    "pnpm-workspace.yaml": 'packages:\n  - "apps/*"\n  - "packages/*"\n',
    "teleforge.config.ts": generatedConfig(options),
    "tsconfig.base.json": generatedBaseTsconfig(),
    "apps/api/package.json": generatedApiPackageJson(packageNames),
    "apps/api/src/index.ts": apiIndexTs(),
    "apps/api/src/flow-hooks/start/home.ts": apiFlowHookTs(),
    "apps/api/src/routes/health.ts": apiHealthRouteTs(),
    "apps/api/src/routes/webhook.ts": apiWebhookRouteTs(),
    "apps/api/tsconfig.json": apiTsconfig(),
    "apps/bot/package.json": generatedBotPackageJson(packageNames),
    "apps/bot/src/flows/start.flow.ts": botStartFlowTs(options.appName, packageNames),
    "apps/bot/src/index.ts": botIndexTs(),
    "apps/bot/src/runtime.ts": botRuntimeTs(),
    "apps/bot/test/start.test.ts": botStartTestTs(options.appName),
    "apps/bot/tsconfig.json": botTsconfig(),
    "packages/types/package.json": generatedTypesPackageJson(packageNames),
    "packages/types/src/index.ts": generatedTypesIndexTs(),
    "packages/types/tsconfig.json": typesTsconfig(),
    ...generatedWebFiles(options, packageNames)
  };
}

function getPackageNames(appId: string): PackageNames {
  const scope = `@${appId}`;

  return {
    api: `${scope}/api`,
    bot: `${scope}/bot`,
    types: `${scope}/types`,
    web: `${scope}/web`
  };
}

function generatedReadme(options: BuildProjectFilesOptions): string {
  const install = `pnpm install`;
  const run = `pnpm run dev`;
  const runPublic = `pnpm run dev:public`;
  const doctor = `pnpm run doctor`;
  const runTests = `pnpm test`;

  return `# ${options.appName}

Teleforge starter workspace generated by \`create-teleforge-app\`.

## Quick Start

\`\`\`bash
${install}
cp .env.example .env
${run}
\`\`\`

For a Telegram-openable URL:

\`\`\`bash
${runPublic}
\`\`\`

Run the baseline scaffold tests with:

\`\`\`bash
${runTests}
\`\`\`

Check setup health with:

\`\`\`bash
${doctor}
\`\`\`

## Structure

- \`apps/web\`: Mini App shell, screens, and styles
- \`apps/bot\`: Bot runtime, discovered flows, and simulator bridge export in \`src/runtime.ts\`
- \`apps/api\`: optional server-hook and webhook placeholders
- \`packages/types\`: shared domain contracts used by bot, web, and server code
- \`teleforge.config.ts\`: App definition

## Read These Files First

- \`teleforge.config.ts\`: source of truth for app identity, flow discovery, and Mini App defaults
- \`apps/bot/src/flows/start.flow.ts\`: the first flow users hit, including its bot entry command and Mini App route
- \`apps/bot/src/runtime.ts\`: where Teleforge discovers flows and boots the bot runtime
- \`packages/types/src/index.ts\`: shared app state and domain contracts
- \`apps/web/src/main.tsx\`: the framework-owned Mini App shell entrypoint
- \`apps/web/src/screens/home.screen.tsx\`: the first Mini App screen module
- \`apps/web/src/teleforge-generated/client-flow-manifest.ts\`: framework-generated client-safe flow metadata for the Mini App shell

The scaffold intentionally starts with one shared state type, one flow, and one screen. Run \`teleforge generate client-manifest\` to regenerate the client manifest after flow changes. Add more domain contracts, flow files, and screen modules as the app grows.

## Dev Workflow

- \`pnpm run dev\`: local simulator with chat, embedded Mini App, fixtures, replay controls, debug panel, and companion bot process
- \`pnpm run dev:public\`: public HTTPS tunnel for real Telegram testing
- \`pnpm test\`: baseline bot and screen smoke tests
- \`pnpm run doctor\`: config and environment diagnostics

## Bot Runtime

- the scaffold runs the bot in polling mode by default
- \`apps/bot/src/runtime.ts\` exports \`createDevBotRuntime()\`, so \`teleforge dev\` can execute bot commands inside the local simulator chat
- use built-in simulator fixtures to jump into fresh-session, dark-mobile, or resume-flow states during local work
- use Replay Last in the simulator to rerun the latest command, callback, or \`web_app_data\` payload while iterating
- leave \`MINI_APP_URL\` blank unless you want to force a fixed override
- \`dev\` and \`dev:public\` inject the resolved local or public URL into the companion bot automatically
- the generated \`apps/api\` files are placeholders; webhook mode only makes sense once the primary web runtime actually serves \`/api/webhook\`

## Runtime Notes

- \`/\`: the generated start flow launches the Mini App here
- \`apps/api\`: stays optional until you need trusted server hooks or a real webhook surface
`;
}

function generatedRootPackageJson(options: BuildProjectFilesOptions): string {
  return stringifyJson({
    name: options.appId,
    private: true,
    version: "1.0.0",
    workspaces: ["apps/*", "packages/*"],
    scripts: {
      dev: "teleforge dev",
      "dev:public": "teleforge dev --public --live",
      doctor: "teleforge doctor",
      generate: "teleforge generate client-manifest",
      predev: "teleforge generate client-manifest",
      "predev:public": "teleforge generate client-manifest",
      prebuild: "teleforge generate client-manifest",
      pretest: "teleforge generate client-manifest",
      lint: "tsc -p tsconfig.base.json --noEmit || echo 'Add eslint or biome to enable linting'",
      typecheck: "tsc -p tsconfig.base.json --noEmit",
      build: "pnpm -r build",
      check: "pnpm typecheck && pnpm test",
      test: "node --import tsx --test apps/bot/test/**/*.test.ts apps/web/test/**/*.test.tsx"
    },
    dependencies: {
      ...teleforgeDependency(options.linkPath),
      dotenv: "^16.4.7"
    },
    devDependencies: {
      tsx: "^4.19.2",
      typescript: "^5.8.3"
    }
  });
}

function generatedConfig(options: BuildProjectFilesOptions): string {
  return `import { defineTeleforgeApp } from "teleforge";

export default defineTeleforgeApp({
  app: {
    id: ${JSON.stringify(options.appId)},
    name: ${JSON.stringify(options.appName)},
    version: "1.0.0"
  },
  flows: {
    root: "apps/bot/src/flows"
  },
  runtime: {
    build: {
      outDir: "dist",
      basePath: "/"
    }
  },
  bot: {
    username: ${JSON.stringify(options.botUsername)},
    tokenEnv: "BOT_TOKEN",
    webhook: {
      path: "/api/webhook",
      secretEnv: "WEBHOOK_SECRET"
    }
  },
  miniApp: {
    entry: "apps/web/src/main.tsx",
    launchModes: ["inline", "compact", "fullscreen"],
    defaultMode: "inline",
    capabilities: ["read_access"]
  }
});
`;
}

function generatedBaseTsconfig(): string {
  return stringifyJson({
    compilerOptions: {
      target: "ES2022",
      strict: true,
      noEmit: true,
      jsx: "react-jsx",
      esModuleInterop: true,
      forceConsistentCasingInFileNames: true,
      skipLibCheck: true
    }
  });
}

function generatedGitignore(): string {
  return `node_modules
dist
.next
.env
.env.local
`;
}

function envExample(): string {
  return `# Bot Configuration
BOT_TOKEN=your_bot_token_here
WEBHOOK_SECRET=your_webhook_secret_here

# Mini App Configuration
TELEGRAM_BOT_USERNAME=your_bot_username
MINI_APP_URL=

# Optional: Development
TELEFORGE_DEV_PORT=3000
TELEFORGE_DEV_HTTPS=true
`;
}

function generatedApiPackageJson(packageNames: PackageNames): string {
  return stringifyJson({
    name: packageNames.api,
    private: true,
    version: "1.0.0",
    type: "module",
    scripts: {
      dev: "tsx watch src/index.ts",
      typecheck: "tsc -p tsconfig.json --noEmit"
    },
    dependencies: {
      [packageNames.types]: "workspace:*"
    }
  });
}

function apiTsconfig(): string {
  return stringifyJson({
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      module: "NodeNext",
      moduleResolution: "NodeNext",
      allowImportingTsExtensions: true
    },
    include: ["src/**/*.ts"]
  });
}

function apiIndexTs(): string {
  return `import { healthRoute } from "./routes/health.ts";
import { webhookRoute } from "./routes/webhook.ts";

export const apiRoutes = [healthRoute, webhookRoute];

export function createApiServer() {
  return {
    routes: apiRoutes,
    description: "Wire these routes into your server runtime when you need trusted server hooks or a standalone webhook surface."
  };
}
`;
}

function apiFlowHookTs(): string {
  return `// Server hook example for the "start" flow, "home" step.
// This file is discovered automatically when the matching flow step needs trusted server logic.
// Remove it if this step does not need guard, loader, or submit handling.

export function guard() {
  return true;
}

export function loader() {
  return {
    heading: "Server-loaded heading"
  };
}

export function onSubmit({ state, data }: { state: unknown; data: unknown }) {
  console.log("Server submit received:", data);
  return {
    state,
    to: "home"
  };
}
`;
}

function apiHealthRouteTs(): string {
  return `export const healthRoute = {
  method: "GET",
  path: "/api/health",
  handler() {
    return {
      ok: true,
      timestamp: new Date().toISOString()
    };
  }
};
`;
}

function apiWebhookRouteTs(): string {
  return `export const webhookRoute = {
  method: "POST",
  path: "/api/webhook",
  handler(payload: unknown) {
    return {
      ok: true,
      received: payload
    };
  }
};
`;
}

function generatedBotPackageJson(packageNames: PackageNames): string {
  return stringifyJson({
    name: packageNames.bot,
    private: true,
    version: "1.0.0",
    type: "module",
    scripts: {
      dev: "tsx watch src/index.ts",
      typecheck: "tsc -p tsconfig.json --noEmit"
    },
    dependencies: {
      [packageNames.types]: "workspace:*"
    }
  });
}

function botTsconfig(): string {
  return stringifyJson({
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      module: "NodeNext",
      moduleResolution: "NodeNext",
      allowImportingTsExtensions: true
    },
    include: ["src/**/*.ts"]
  });
}

function botIndexTs(): string {
  return `import { config as loadDotenv } from "dotenv";
import https from "node:https";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type BotRuntime,
  type BotInstance,
  type RegisteredCommand,
  type ReplyOptions,
  type TelegramMessage,
  type TelegramReplyMarkup,
  type TelegramUpdate
} from "teleforge/bot";

import { createGeneratedBotRuntime, hasUsableToken, readGeneratedBotConfig } from "./runtime.ts";

loadWorkspaceEnv();

const botConfig = readGeneratedBotConfig();

async function main() {
  const runtime = await createGeneratedBotRuntime(botConfig);

  const token = botConfig.token;
  if (!hasUsableToken(token)) {
    await runPreview(runtime);
    keepProcessAlive();
    return;
  }

  const bot = createPollingBot(token);
  runtime.bindBot(bot);
  const commands = runtime.getCommands();
  await bot.setCommands(commands);

  let offset: number | undefined;
  console.log(\`[generated-app:bot] polling Telegram for updates (\${commands.length} commands registered)\`);

  for (;;) {
    const updates = await bot.getUpdates(offset);

    for (const update of updates) {
      offset = typeof update.update_id === "number" ? update.update_id + 1 : offset;
      await runtime.handle(update);
    }
  }
}

main().catch((error) => {
  console.error("[generated-app:bot] fatal error", error);
  process.exitCode = 1;
});

async function runPreview(runtime: BotRuntime) {
  runtime.bindBot({
    async sendMessage(chatId, text, options = {}) {
      console.log(
        "[generated-app:bot:preview]",
        JSON.stringify({
          chatId,
          options,
          text
        })
      );
      return {
        chat: {
          id: chatId,
          type: "private"
        },
        message_id: Date.now(),
        text
      };
    }
  });

  console.log("[generated-app:bot] BOT_TOKEN missing, running in preview mode");

  await runtime.handle({
    message: {
      chat: {
        id: 1,
        type: "private"
      },
      from: {
        first_name: "Preview",
        id: 1,
        username: "preview_user"
      },
      message_id: 1,
      text: "/start"
    },
    update_id: 1
  } satisfies TelegramUpdate);
}

function keepProcessAlive() {
  setInterval(() => {
    // Keep preview mode alive so \`teleforge dev\` keeps both services running.
  }, 60_000);
}

interface PollingBot extends BotInstance {
  getUpdates: (offset?: number) => Promise<TelegramUpdate[]>;
  setCommands: (commands: RegisteredCommand[]) => Promise<void>;
}

function createPollingBot(token: string): PollingBot {
  const apiBaseUrl = \`https://api.telegram.org/bot\${token}\`;

  return {
    async getUpdates(offset?: number): Promise<TelegramUpdate[]> {
      const payload = await callTelegramApi<TelegramUpdate[]>(apiBaseUrl, "getUpdates", {
        allowed_updates: ["message"],
        offset,
        timeout: 25
      });
      return Array.isArray(payload) ? payload : [];
    },
    async sendMessage(chatId: number, text: string, options: ReplyOptions = {}): Promise<TelegramMessage> {
      return callTelegramApi<TelegramMessage>(apiBaseUrl, "sendMessage", {
        chat_id: chatId,
        text,
        ...toTelegramSendMessageOptions(options)
      });
    },
    async setCommands(commands: RegisteredCommand[]) {
      await callTelegramApi(apiBaseUrl, "setMyCommands", {
        commands: commands.map((command) => ({
          command: command.command,
          description: command.description ?? command.command
        }))
      });
    }
  };
}

async function callTelegramApi<TResponse>(
  apiBaseUrl: string,
  method: string,
  body: Record<string, unknown>
): Promise<TResponse> {
  let lastError: unknown;

  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      const response = await postJson(\`\${apiBaseUrl}/\${method}\`, body);
      const payload = JSON.parse(response.body) as {
        description?: string;
        ok?: boolean;
        result?: TResponse;
      };

      if (response.statusCode < 200 || response.statusCode >= 300 || !payload.ok) {
        throw new Error(payload.description ?? \`Telegram API \${method} failed\`);
      }

      return payload.result as TResponse;
    } catch (error) {
      lastError = error;

      if (!isRetryableTelegramNetworkError(error) || attempt === 3) {
        break;
      }

      await sleep(attempt * 500);
    }
  }

  if (lastError instanceof Error) {
    throw new Error(\`Telegram API \${method} failed: \${lastError.message}\`, { cause: lastError });
  }

  throw new Error(\`Telegram API \${method} failed\`);
}

function toTelegramSendMessageOptions(options: ReplyOptions): Record<string, unknown> {
  return {
    disable_web_page_preview: options.disable_web_page_preview,
    parse_mode: options.parse_mode,
    reply_markup: serializeReplyMarkup(options.reply_markup),
    reply_to_message_id: options.reply_to_message_id
  };
}

function serializeReplyMarkup(markup?: TelegramReplyMarkup): TelegramReplyMarkup | undefined {
  return markup ? { ...markup } : undefined;
}

interface JsonResponse {
  body: string;
  statusCode: number;
}

function postJson(url: string, body: Record<string, unknown>): Promise<JsonResponse> {
  const payload = JSON.stringify(body);
  const target = new URL(url);
  const timeoutSeconds = typeof body.timeout === "number" ? body.timeout : 0;
  const timeoutMs = Math.max(10_000, (timeoutSeconds + 10) * 1_000);

  return new Promise<JsonResponse>((resolve, reject) => {
    const request = https.request(
      {
        family: 4,
        headers: {
          "content-length": Buffer.byteLength(payload),
          "content-type": "application/json"
        },
        hostname: target.hostname,
        method: "POST",
        path: \`\${target.pathname}\${target.search}\`,
        port: target.port ? Number(target.port) : 443
      },
      (response) => {
        let responseBody = "";

        response.setEncoding("utf8");
        response.on("data", (chunk) => {
          responseBody += chunk;
        });
        response.on("end", () => {
          resolve({
            body: responseBody,
            statusCode: response.statusCode ?? 0
          });
        });
      }
    );

    request.setTimeout(timeoutMs, () => {
      request.destroy(new Error(\`Telegram API request timed out after \${timeoutMs}ms.\`));
    });
    request.on("error", (error) => {
      reject(error);
    });
    request.write(payload);
    request.end();
  });
}

function isRetryableTelegramNetworkError(error: unknown): boolean {
  if (!(error instanceof Error)) {
    return false;
  }

  const nodeError = error as Error & { code?: string };
  return (
    nodeError.code === "ECONNRESET" ||
    nodeError.code === "ENETUNREACH" ||
    nodeError.code === "ETIMEDOUT" ||
    error.message.includes("timed out")
  );
}

function sleep(timeoutMs: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, timeoutMs);
  });
}

function loadWorkspaceEnv() {
  const workspaceRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
  const envPaths = [resolve(workspaceRoot, ".env"), resolve(workspaceRoot, ".env.local")];

  for (const envPath of envPaths) {
    if (!existsSync(envPath)) {
      continue;
    }

    loadDotenv({
      override: envPath.endsWith(".env.local"),
      path: envPath
    });
  }
}

`;
}

function botRuntimeTs(): string {
  return `import { config as loadDotenv } from "dotenv";
import { createDiscoveredBotRuntime } from "teleforge";
import { type BotRuntime } from "teleforge/bot";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export interface GeneratedBotRuntimeOptions {
  flowSecret?: string;
  miniAppUrl?: string;
  workspaceRoot?: string;
}

export interface GeneratedBotConfig {
  flowSecret: string;
  miniAppUrl: string;
  token?: string;
  workspaceRoot: string;
}

loadWorkspaceEnv();

export function createGeneratedBotRuntime(
  options: GeneratedBotRuntimeOptions = {}
): Promise<BotRuntime> {
  const config = readGeneratedBotConfig(options);

  return createDiscoveredBotRuntime({
    cwd: config.workspaceRoot,
    flowSecret: config.flowSecret,
    miniAppUrl: config.miniAppUrl
  });
}

export async function createDevBotRuntime(
  options: GeneratedBotRuntimeOptions = {}
): Promise<BotRuntime> {
  return createGeneratedBotRuntime(options);
}

export function readGeneratedBotConfig(
  options: GeneratedBotRuntimeOptions = {}
): GeneratedBotConfig {
  const workspaceRoot =
    readNonEmptyEnvValue(options.workspaceRoot) ??
    resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

  return {
    flowSecret:
      readNonEmptyEnvValue(options.flowSecret) ??
      readNonEmptyEnv("TELEFORGE_FLOW_SECRET") ??
      "teleforge-generated-flow-secret",
    miniAppUrl:
      readNonEmptyEnvValue(options.miniAppUrl) ??
      readNonEmptyEnv("MINI_APP_URL") ??
      "https://example.ngrok.app",
    token: readNonEmptyEnv("BOT_TOKEN"),
    workspaceRoot
  };
}

function loadWorkspaceEnv() {
  const workspaceRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
  const envPaths = [resolve(workspaceRoot, ".env"), resolve(workspaceRoot, ".env.local")];

  for (const envPath of envPaths) {
    if (!existsSync(envPath)) {
      continue;
    }

    loadDotenv({
      override: envPath.endsWith(".env.local"),
      path: envPath
    });
  }
}

function readNonEmptyEnv(name: string): string | undefined {
  return readNonEmptyEnvValue(process.env[name]);
}

function readNonEmptyEnvValue(value: string | undefined): string | undefined {
  if (!value) {
    return undefined;
  }

  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

export function hasUsableToken(value: string | undefined): value is string {
  if (!value) {
    return false;
  }

  const trimmed = value.trim();
  const normalized = trimmed.toLowerCase();
  return (
    trimmed.includes(":") &&
    !normalized.includes("your_") &&
    !normalized.includes("placeholder")
  );
}
`;
}

function botStartFlowTs(appName: string, packageNames: PackageNames): string {
  return `import { defineFlow } from "teleforge/web";
import type { StartFlowState } from "${packageNames.types}";

export default defineFlow<StartFlowState>({
  id: "start",
  initialStep: "home",
  state: {
    visited: false
  },
  bot: {
    command: {
      buttonText: "Open ${appName}",
      command: "start",
      description: "Start the Mini App",
      text: "Welcome to ${appName}. Launch the Mini App to continue."
    }
  },
  miniApp: {
    launchModes: ["inline", "compact", "fullscreen"],
    route: "/"
  },
  steps: {
    home: {
      screen: "home",
      type: "miniapp"
    }
  }
});
`;
}

function botStartTestTs(appName: string): string {
  return `import assert from "node:assert/strict";
import test from "node:test";

import startFlow from "../src/flows/start.flow.ts";

test("start flow declares the bot entry command", () => {
  assert.equal(startFlow.bot?.command?.command, "start");
  assert.equal(startFlow.bot?.command?.buttonText, "Open ${appName}");
  assert.match(
    startFlow.bot?.command?.text ?? "",
    /Welcome to ${appName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/
  );
  assert.equal(startFlow.miniApp?.route, "/");
  assert.equal(startFlow.steps.home.type, "miniapp");
});
`;
}

function generatedWebFiles(
  options: BuildProjectFilesOptions,
  packageNames: PackageNames
): Record<string, string> {
  return {
    "apps/web/index.html": spaIndexHtml(options.appName),
    "apps/web/package.json": stringifyJson({
      name: packageNames.web,
      private: true,
      version: "1.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
        typecheck: "tsc -p tsconfig.json --noEmit"
      },
      dependencies: {
        [packageNames.types]: "workspace:*",
        react: "^18.3.1",
        "react-dom": "^18.3.1"
      },
      devDependencies: {
        "@types/react": "^18.3.12",
        "@types/react-dom": "^18.3.1",
        "@vitejs/plugin-react": "^4.3.1",
        vite: "^5.4.10"
      }
    }),
    "apps/web/src/App.tsx": webAppTsx(options.appName),
    "apps/web/src/main.tsx": webMainTsx(),
    "apps/web/src/screens/home.screen.tsx": homeScreenTsx(packageNames),
    "apps/web/src/styles.css": webStylesCss(),
    "apps/web/test/home.test.tsx": homePageTestTs(options.appName),
    "apps/web/tsconfig.json": stringifyJson({
      extends: "../../tsconfig.base.json",
      compilerOptions: {
        module: "ESNext",
        moduleResolution: "Bundler"
      },
      include: ["src/**/*.ts", "src/**/*.tsx"]
    }),
    "apps/web/vite.config.ts": viteConfigTs()
  };
}

function generatedTypesPackageJson(packageNames: PackageNames): string {
  return stringifyJson({
    name: packageNames.types,
    private: true,
    version: "1.0.0",
    type: "module",
    exports: {
      ".": "./src/index.ts"
    },
    scripts: {
      typecheck: "tsc -p tsconfig.json --noEmit"
    }
  });
}

function generatedTypesIndexTs(): string {
  return `export interface StartFlowState {
  visited: boolean;
}
`;
}

function typesTsconfig(): string {
  return stringifyJson({
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      module: "NodeNext",
      moduleResolution: "NodeNext",
      allowImportingTsExtensions: true
    },
    include: ["src/**/*.ts"]
  });
}

function spaIndexHtml(appName: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function viteConfigTs(): string {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()]
});
`;
}

function webMainTsx(): string {
  return `import React from "react";
import ReactDOM from "react-dom/client";
import { TeleforgeMiniApp } from "teleforge/web";

import { flowManifest } from "./teleforge-generated/client-flow-manifest.js";
import homeScreen from "./screens/home.screen.js";
import "./styles.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <TeleforgeMiniApp flowManifest={flowManifest} screens={[homeScreen]} />
  </React.StrictMode>
);
`;
}

function webAppTsx(appName: string): string {
  return `import React from "react";

export default function App() {
  return (
    <main className="shell">
      <header className="hero">
        <p className="eyebrow">Teleforge Starter</p>
        <h1>${appName}</h1>
        <p className="lede">
          Generated with the unified Teleforge scaffold. This screen is mounted through the
          framework-owned Mini App runtime instead of an app-local router.
        </p>
      </header>
      <section className="card stack">
        <p className="badge">Screen: home</p>
        <h2>Welcome to ${appName}</h2>
        <p>
          Start from flows and screens. Add more \`.flow.ts\` modules in \`apps/bot/src/flows\`
          and more \`.screen.tsx\` modules in \`apps/web/src/screens\` as the product grows.
        </p>
      </section>
    </main>
  );
}
`;
}

function homeScreenTsx(packageNames: PackageNames): string {
  return `import { defineScreen } from "teleforge/web";
import type { StartFlowState } from "${packageNames.types}";

import App from "../App.js";

export default defineScreen<StartFlowState>({
  component() {
    return <App />;
  },
  id: "home",
  title: "Home"
});
`;
}

function homePageTestTs(appName: string): string {
  return `import assert from "node:assert/strict";
import test from "node:test";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

import App from "../src/App";

test("home screen renders the welcome screen", () => {
  const html = renderToStaticMarkup(<App />);

  assert.match(html, /Welcome to ${appName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/);
  assert.match(html, /Screen: home/);
});
`;
}

function webStylesCss(): string {
  return `:root {
  color-scheme: light;
  font-family: "IBM Plex Sans", sans-serif;
  background:
    radial-gradient(circle at top left, rgba(76, 175, 80, 0.18), transparent 32%),
    radial-gradient(circle at top right, rgba(33, 150, 243, 0.14), transparent 28%),
    #f5f7fb;
  color: #18212f;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
}

a,
button {
  border: 0;
  background: #18212f;
  color: #ffffff;
  border-radius: 999px;
  padding: 0.7rem 1rem;
  cursor: pointer;
  font: inherit;
  text-decoration: none;
}

.shell {
  width: min(960px, calc(100% - 2rem));
  margin: 0 auto;
  padding: 3rem 0 4rem;
}

.hero {
  display: grid;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.hero h1,
.card h2 {
  margin: 0;
}

.eyebrow,
.badge {
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-size: 0.85rem;
  color: #4f5d75;
}

.lede {
  max-width: 48rem;
  line-height: 1.6;
}

.nav {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
}

.card {
  background: rgba(255, 255, 255, 0.88);
  backdrop-filter: blur(14px);
  border: 1px solid rgba(24, 33, 47, 0.08);
  border-radius: 24px;
  padding: 1.5rem;
  box-shadow: 0 20px 60px rgba(24, 33, 47, 0.08);
}

.stack {
  display: grid;
  gap: 0.75rem;
}
`;
}

function stringifyJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}
