interface BuildProjectFilesOptions {
  appId: string;
  appName: string;
  botUsername: string;
  /** When set, use `link:` protocol pointing to this local teleforge monorepo path. */
  linkPath?: string;
}

interface PackageNames {
  api: string;
  bot: string;
  types: string;
  web: string;
}

function teleforgeDependency(linkPath?: string): Record<string, string> {
  return {
    teleforge: !linkPath ? "^0.5.0" : `link:${linkPath}/packages/teleforge`
  };
}

export function buildProjectFiles(options: BuildProjectFilesOptions): Record<string, string> {
  const packageNames = getPackageNames(options.appId);

  return {
    ".env.example": envExample(),
    ".gitignore": generatedGitignore(),
    "README.md": generatedReadme(options),
    "package.json": generatedRootPackageJson(options),
    "pnpm-workspace.yaml": 'packages:\n  - "apps/*"\n  - "packages/*"\n',
    "teleforge.config.ts": generatedConfig(options),
    "tsconfig.base.json": generatedBaseTsconfig(),
    ...generatedApiFiles(packageNames),
    "apps/bot/package.json": generatedBotPackageJson(packageNames),
    "apps/bot/src/flows/start.flow.ts": botStartFlowTs(options.appName, packageNames),
    "apps/bot/src/index.ts": botIndexTs(),
    "apps/bot/src/runtime.ts": botRuntimeTs(),
    "apps/bot/test/start.test.ts": botStartTestTs(options.appName),
    "apps/bot/tsconfig.json": botTsconfig(),
    "packages/types/package.json": generatedTypesPackageJson(packageNames),
    "packages/types/src/index.ts": generatedTypesIndexTs(),
    "packages/types/tsconfig.json": typesTsconfig(),
    ...generatedWebFiles(options, packageNames)
  };
}

function getPackageNames(appId: string): PackageNames {
  const scope = `@${appId}`;

  return {
    api: `${scope}/api`,
    bot: `${scope}/bot`,
    types: `${scope}/types`,
    web: `${scope}/web`
  };
}

function generatedApiFiles(packageNames: PackageNames): Record<string, string> {
  return {
    "apps/api/package.json": generatedApiPackageJson(packageNames),
    "apps/api/src/index.ts": apiIndexTs(),
    "apps/api/src/loaders/home.loader.ts": homeLoaderTs(),
    "apps/api/tsconfig.json": apiTsconfig()
  };
}

function generatedReadme(options: BuildProjectFilesOptions): string {
  const install = `pnpm install`;
  const run = `pnpm run dev`;
  const runPublic = `pnpm run dev:public`;
  const doctor = `pnpm run doctor`;
  const runTests = `pnpm test`;
  const generate = `pnpm run generate`;

  return `# ${options.appName}

Teleforge starter workspace generated by \`teleforge create\`.

## Quick Start

\`\`\`bash
${install}
cp .env.example .env
${generate}
${run}
\`\`\`

For a Telegram-openable URL with public HTTPS:

\`\`\`bash
${runPublic}
\`\`\`

Run the baseline scaffold tests with:

\`\`\`bash
${runTests}
\`\`\`

Check setup health with:

\`\`\`bash
${doctor}
\`\`\`

## Structure

- \`apps/web\`: Mini App shell, screens, and styles
- \`apps/bot\`: Discovered flows plus the bot/server runtime
- \`apps/api\`: Server loaders for Mini App screens
- \`packages/types\`: Shared types (generated contracts live in apps/web/src/teleforge-generated/)
- \`teleforge.config.ts\`: App definition

## Read These Files First

- \`teleforge.config.ts\`: source of truth for app identity, flow discovery, and Mini App defaults
- \`apps/bot/src/flows/start.flow.ts\`: the first flow with bot command and actions
- \`apps/api/src/loaders/home.loader.ts\`: server loader for the home screen
- \`apps/web/src/main.tsx\`: the Mini App shell entrypoint
- \`apps/web/src/screens/home.screen.tsx\`: the first Mini App screen with typed props
- \`apps/web/src/teleforge-contract-overrides.ts\`: typed payload and loader data overrides

The scaffold starts with one flow, one screen, one action, and one loader. \`pnpm run generate\` creates:
- \`apps/web/src/teleforge-generated/client-flow-manifest.ts\`
- \`apps/web/src/teleforge-generated/contracts.ts\`

These are refreshed automatically before dev, test, and build.

## Dev Workflow

- \`pnpm run dev\`: local simulator with chat, embedded Mini App, fixtures, and debug panel
- \`pnpm run dev:public\`: public HTTPS tunnel for real Telegram testing
- \`pnpm test\`: baseline bot and screen smoke tests
- \`pnpm run doctor\`: config, manifest, and environment diagnostics
- \`pnpm run generate\`: regenerate client manifest and typed contracts

## Next Steps

Add more flows in \`apps/bot/src/flows\`, more screens in \`apps/web/src/screens\`, and more loaders in \`apps/api/src/loaders\`. See the Teleforge docs for:

- [Runtime Wiring](https://teleforge.dev/docs/runtime-wiring)
- [State Boundaries](https://teleforge.dev/docs/state-boundaries)
- [Generated Mini App Contracts](https://teleforge.dev/docs/generated-miniapp-contracts)
- [Server Loaders](https://teleforge.dev/docs/server-hooks)
`;
}

function generatedRootPackageJson(options: BuildProjectFilesOptions): string {
  return stringifyJson({
    name: options.appId,
    private: true,
    version: "1.0.0",
    workspaces: ["apps/*", "packages/*"],
    scripts: {
      dev: "teleforge dev",
      "dev:public": "teleforge dev --public --live",
      doctor: "teleforge doctor",
      generate: "teleforge generate client-manifest",
      predev: "teleforge generate client-manifest",
      "predev:public": "teleforge generate client-manifest",
      prebuild: "teleforge generate client-manifest",
      pretest: "teleforge generate client-manifest",
      pretypecheck: "teleforge generate client-manifest",
      lint: "pnpm -r --if-present typecheck || echo 'Add eslint or biome to enable linting'",
      typecheck: "pnpm -r --if-present typecheck",
      build: "pnpm -r build",
      check: "pnpm typecheck && pnpm test",
      test: "node --import tsx --test apps/bot/test/**/*.test.ts apps/web/test/**/*.test.tsx"
    },
    dependencies: {
      ...teleforgeDependency(options.linkPath),
      dotenv: "^16.4.7"
    },
    devDependencies: {
      "@types/node": "24.12.0",
      tsx: "^4.19.2",
      typescript: "^5.8.3"
    }
  });
}

function generatedConfig(options: BuildProjectFilesOptions): string {
  return `import { defineTeleforgeApp } from "teleforge";

export default defineTeleforgeApp({
  app: {
    id: ${JSON.stringify(options.appId)},
    name: ${JSON.stringify(options.appName)},
    version: "1.0.0"
  },
  flows: {
    root: "apps/bot/src/flows"
  },
  runtime: {
    build: {
      outDir: "dist",
      basePath: "/"
    }
  },
  bot: {
    username: ${JSON.stringify(options.botUsername)},
    tokenEnv: "BOT_TOKEN"
  },
  miniApp: {
    entry: "apps/web/src/main.tsx",
    launchModes: ["inline", "compact", "fullscreen"],
    defaultMode: "inline",
    capabilities: ["read_access"]
  }
});
`;
}

function generatedBaseTsconfig(): string {
  return stringifyJson({
    compilerOptions: {
      target: "ES2022",
      strict: true,
      noEmit: true,
      jsx: "react-jsx",
      esModuleInterop: true,
      forceConsistentCasingInFileNames: true,
      skipLibCheck: true
    }
  });
}

function generatedGitignore(): string {
  return `node_modules
dist
.next
.env
.env.local
`;
}

function envExample(): string {
  return `# Bot Configuration
BOT_TOKEN=your_bot_token_here

# Mini App Configuration
TELEGRAM_BOT_USERNAME=your_bot_username
MINI_APP_URL=
TELEFORGE_FLOW_SECRET=

# Optional: Development
TELEFORGE_DEV_PORT=3000
`;
}

function generatedApiPackageJson(packageNames: PackageNames): string {
  return stringifyJson({
    name: packageNames.api,
    private: true,
    version: "1.0.0",
    type: "module",
    scripts: {
      dev: "tsx watch src/index.ts",
      typecheck: "tsc -p tsconfig.json --noEmit"
    },
    dependencies: {
      [packageNames.types]: "workspace:*"
    }
  });
}

function apiTsconfig(): string {
  return stringifyJson({
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      module: "NodeNext",
      moduleResolution: "NodeNext",
      allowImportingTsExtensions: true
    },
    include: ["src/**/*.ts"]
  });
}

function apiIndexTs(): string {
  return `// API server entry point
// The Teleforge server bridge loads loaders automatically based on screen IDs.
// This file is kept minimal for the starter scaffold.

export {};
`;
}

function homeLoaderTs(): string {
  return `import { defineLoader } from "teleforge";

export default defineLoader({
  handler: async () => {
    return {
      greeting: "Welcome from the Teleforge server loader"
    };
  }
});
`;
}

function generatedBotPackageJson(packageNames: PackageNames): string {
  return stringifyJson({
    name: packageNames.bot,
    private: true,
    version: "1.0.0",
    type: "module",
    scripts: {
      dev: "tsx watch src/index.ts",
      typecheck: "tsc -p tsconfig.json --noEmit"
    },
    dependencies: {
      [packageNames.types]: "workspace:*"
    }
  });
}

function botTsconfig(): string {
  return stringifyJson({
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      module: "NodeNext",
      moduleResolution: "NodeNext",
      allowImportingTsExtensions: true
    },
    include: ["src/**/*.ts"]
  });
}

function botIndexTs(): string {
  return `import path from "node:path";
import { fileURLToPath } from "node:url";

import { createTeleforgeRuntimeContext, startTeleforgeBot, startTeleforgeServer } from "teleforge";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

const context = await createTeleforgeRuntimeContext({
  cwd: projectRoot
});

const { runtime, stop: stopBot } = await startTeleforgeBot({
  app: context.app,
  cwd: context.cwd,
  flowSecret: context.flowSecret,
  miniAppUrl: context.miniAppUrl,
  sessionManager: context.sessionManager,
  services: context.services
});

const { stop: stopServer } = await startTeleforgeServer({
  app: context.app,
  cwd: context.cwd,
  flowSecret: context.flowSecret,
  miniAppUrl: context.miniAppUrl,
  sessionManager: context.sessionManager,
  services: context.services,
  onChatHandoff: (input) => runtime.handleChatHandoff(input)
});

process.on("SIGINT", () => {
  console.log("\\n[bot] shutting down...");
  stopBot();
  stopServer();
  process.exit(0);
});

process.on("SIGTERM", () => {
  console.log("\\n[bot] shutting down...");
  stopBot();
  stopServer();
  process.exit(0);
});
`;
}

function botRuntimeTs(): string {
  return `import path from "node:path";
import { fileURLToPath } from "node:url";

import { startTeleforgeBot } from "teleforge";
import { type BotRuntime } from "teleforge/bot";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

export async function createDevBotRuntime(options?: { miniAppUrl?: string }): Promise<BotRuntime> {
  const { runtime } = await startTeleforgeBot({
    cwd: projectRoot,
    miniAppUrl: options?.miniAppUrl
  });
  return runtime;
}
`;
}

function botStartFlowTs(appName: string, _packageNames: PackageNames): string {
  return `import { defineFlow } from "teleforge";

export default defineFlow({
  id: "start",
  command: {
    command: "start",
    description: "Start the Mini App",
    handler: async ({ ctx, sign }) => {
      const url = await sign({
        screenId: "home",
        subject: { resource: { type: "welcome" } },
        allowedActions: ["acknowledge"]
      });

      await ctx.reply("Welcome to ${appName}. Open the Mini App to continue.", {
        reply_markup: {
          inline_keyboard: [[{ text: "Open App", web_app: { url } }]]
        }
      });
    }
  },
  miniApp: {
    routes: { "/": "home" },
    defaultRoute: "/",
    title: "${appName}"
  },
  actions: {
    acknowledge: {
      handler: async () => {
        return { data: { acknowledged: true } };
      }
    }
  }
});
`;
}

function botStartTestTs(appName: string): string {
  return `import assert from "node:assert/strict";
import test from "node:test";

import startFlow from "../src/flows/start.flow.ts";

test("start flow declares the bot entry command", () => {
  assert.equal(startFlow.command?.command, "start");
  assert.equal(startFlow.command?.description, "Start the Mini App");
  assert.equal(startFlow.miniApp?.routes["/"], "home");
  assert.equal(startFlow.miniApp?.defaultRoute, "/");
  assert.ok(startFlow.actions?.acknowledge);
  assert.ok(startFlow.actions.acknowledge.handler);
});
`;
}

function generatedWebFiles(
  options: BuildProjectFilesOptions,
  _packageNames: PackageNames
): Record<string, string> {
  return {
    "apps/web/index.html": spaIndexHtml(options.appName),
    "apps/web/package.json": stringifyJson({
      name: `@${options.appId}/web`,
      private: true,
      version: "1.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
        typecheck: "tsc -p tsconfig.json --noEmit"
      },
      dependencies: {
        [`@${options.appId}/types`]: "workspace:*",
        react: "^18.3.1",
        "react-dom": "^18.3.1"
      },
      devDependencies: {
        "@types/react": "^18.3.12",
        "@types/react-dom": "^18.3.1",
        "@vitejs/plugin-react": "^4.3.1",
        vite: "^5.4.10"
      }
    }),
    "apps/web/src/main.tsx": webMainTsx(),
    "apps/web/src/screens/home.screen.tsx": homeScreenTsx(),
    "apps/web/src/teleforge-contract-overrides.ts": contractOverridesTs(),
    "apps/web/src/styles.css": webStylesCss(),
    "apps/web/test/home.test.tsx": homePageTestTs(options.appName),
    "apps/web/tsconfig.json": stringifyJson({
      extends: "../../tsconfig.base.json",
      compilerOptions: {
        module: "ESNext",
        moduleResolution: "Bundler"
      },
      include: ["src/**/*.ts", "src/**/*.tsx", "test/**/*.tsx"]
    }),
    "apps/web/vite.config.ts": viteConfigTs()
  };
}

function generatedTypesPackageJson(packageNames: PackageNames): string {
  return stringifyJson({
    name: packageNames.types,
    private: true,
    version: "1.0.0",
    type: "module",
    exports: {
      ".": "./src/index.ts"
    },
    scripts: {
      typecheck: "tsc -p tsconfig.json --noEmit"
    }
  });
}

function generatedTypesIndexTs(): string {
  return `// Shared types for the workspace
// Flow-specific types are now generated in apps/web/src/teleforge-generated/contracts.ts

export {};
`;
}

function typesTsconfig(): string {
  return stringifyJson({
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      module: "NodeNext",
      moduleResolution: "NodeNext",
      allowImportingTsExtensions: true
    },
    include: ["src/**/*.ts"]
  });
}

function spaIndexHtml(appName: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function viteConfigTs(): string {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      "/api/teleforge": "http://localhost:3100"
    }
  }
});
`;
}

function webMainTsx(): string {
  return `import React from "react";
import ReactDOM from "react-dom/client";
import { TeleforgeMiniApp, createFetchMiniAppServerBridge } from "teleforge/web";

import { flowManifest } from "./teleforge-generated/client-flow-manifest.js";
import homeScreen from "./screens/home.screen.js";
import "./styles.css";

const serverBridge = createFetchMiniAppServerBridge();

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <TeleforgeMiniApp
      flowManifest={flowManifest}
      screens={[homeScreen]}
      serverBridge={serverBridge}
    />
  </React.StrictMode>
);
`;
}

function homeScreenTsx(): string {
  return `import React from "react";
import { defineScreen } from "teleforge/web";
import type { HomeScreenProps } from "../teleforge-generated/contracts";

export function HomeScreen({ loader, loaderData, actions }: HomeScreenProps) {
  if (loader.status === "loading") return <main>Loading...</main>;
  if (loader.status === "error") return <main>Could not load.</main>;

  return (
    <main className="shell">
      <header className="hero">
        <p className="eyebrow">Teleforge Starter</p>
        <h1>{loaderData?.greeting ?? "Welcome"}</h1>
        <p className="lede">
          Generated with the unified Teleforge scaffold. This screen uses typed props from
          generated contracts and demonstrates the server loader pattern.
        </p>
      </header>
      <section className="card stack">
        <p className="badge">Screen: home</p>
        <h2>Getting Started</h2>
        <p>
          Start from flows and screens. Add more \`.flow.ts\` modules in \`apps/bot/src/flows\`
          and more \`.screen.tsx\` modules in \`apps/web/src/screens\` as the product grows.
        </p>
        <button onClick={() => actions.acknowledge()}>Continue</button>
      </section>
    </main>
  );
}

export default defineScreen<HomeScreenProps>({
  id: "home",
  title: "Home",
  component: HomeScreen
});
`;
}

function contractOverridesTs(): string {
  return `export interface TeleforgeActionPayloadOverrides {
  start: {
    acknowledge: undefined;
  };
}

export interface TeleforgeLoaderDataOverrides {
  start: {
    home: {
      greeting: string;
    };
  };
}
`;
}

function homePageTestTs(appName: string): string {
  return `import assert from "node:assert/strict";
import test from "node:test";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

import { HomeScreen } from "../src/screens/home.screen";
import type { HomeScreenProps } from "../src/teleforge-generated/contracts";

test("home screen renders the welcome screen", () => {
  const mockLoaderData = { greeting: "Test greeting" };

  const props = {
    screenId: "home" as const,
    routePath: "/",
    routeParams: {},
    scopeData: undefined,
    routeData: undefined,
    appState: undefined,
    loader: { status: "ready" as const, data: mockLoaderData },
    loaderData: mockLoaderData,
    actions: { acknowledge: async () => ({ data: { acknowledged: true } }) },
    nav: { home: () => {} },
    runAction: async () => ({ data: {} }),
    navigate: () => {},
    transitioning: false
  } satisfies HomeScreenProps;

  const html = renderToStaticMarkup(<HomeScreen {...props} />);

  assert.match(html, /Test greeting/);
  assert.match(html, /Screen: home/);
});
`;
}

function webStylesCss(): string {
  return `:root {
  color-scheme: light;
  font-family: "IBM Plex Sans", sans-serif;
  background:
    radial-gradient(circle at top left, rgba(76, 175, 80, 0.18), transparent 32%),
    radial-gradient(circle at top right, rgba(33, 150, 243, 0.14), transparent 28%),
    #f5f7fb;
  color: #18212f;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
}

a,
button {
  border: 0;
  background: #18212f;
  color: #ffffff;
  border-radius: 999px;
  padding: 0.7rem 1rem;
  cursor: pointer;
  font: inherit;
  text-decoration: none;
}

.shell {
  width: min(960px, calc(100% - 2rem));
  margin: 0 auto;
  padding: 3rem 0 4rem;
}

.hero {
  display: grid;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.hero h1,
.card h2 {
  margin: 0;
}

.eyebrow,
.badge {
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-size: 0.85rem;
  color: #4f5d75;
}

.lede {
  max-width: 48rem;
  line-height: 1.6;
}

.nav {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
}

.card {
  background: rgba(255, 255, 255, 0.88);
  backdrop-filter: blur(14px);
  border: 1px solid rgba(24, 33, 47, 0.08);
  border-radius: 24px;
  padding: 1.5rem;
  box-shadow: 0 20px 60px rgba(24, 33, 47, 0.08);
}

.stack {
  display: grid;
  gap: 0.75rem;
}
`;
}

function stringifyJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}
