import type { GeneratorMode, PackageManager } from "./generator.js";

interface BuildProjectFilesOptions {
  appId: string;
  appName: string;
  botUsername: string;
  mode: GeneratorMode;
  packageManager: PackageManager;
}

const teleforgeDependencies = {
  "@teleforge/bot": "^1.0.0",
  "@teleforge/core": "^1.0.0",
  "@teleforge/ui": "^1.0.0",
  "@teleforge/web": "^1.0.0"
};

export function buildProjectFiles(options: BuildProjectFilesOptions): Record<string, string> {
  return {
    ".env.example": envExample(),
    ".gitignore": generatedGitignore(),
    "README.md": generatedReadme(options),
    "package.json": generatedRootPackageJson(options),
    "pnpm-workspace.yaml": 'packages:\n  - "apps/*"\n',
    "teleforge.app.json": generatedManifest(options),
    "tsconfig.base.json": generatedBaseTsconfig(),
    "apps/api/package.json": generatedApiPackageJson(),
    "apps/api/src/index.ts": apiIndexTs(),
    "apps/api/src/routes/health.ts": apiHealthRouteTs(),
    "apps/api/src/routes/webhook.ts": apiWebhookRouteTs(),
    "apps/api/tsconfig.json": apiTsconfig(),
    "apps/bot/package.json": generatedBotPackageJson(),
    "apps/bot/src/commands/start.ts": botStartCommandTs(options.appName),
    "apps/bot/src/index.ts": botIndexTs(),
    "apps/bot/tsconfig.json": botTsconfig(),
    ...generatedWebFiles(options)
  };
}

function generatedReadme(options: BuildProjectFilesOptions): string {
  const install = `${options.packageManager} install`;
  const run = `${options.packageManager} run dev`;
  const doctor = `${options.packageManager} run doctor`;

  return `# ${options.appName}

Teleforge starter workspace generated by \`create-teleforge-app\`.

## Quick Start

\`\`\`bash
${install}
cp .env.example .env
${run}
\`\`\`

Check setup health with:

\`\`\`bash
${doctor}
\`\`\`

## Structure

- \`apps/web\`: Mini App surface (${options.mode === "spa" ? "Vite SPA" : "Next.js BFF web"})
- \`apps/bot\`: Bot runtime and command handlers
- \`apps/api\`: API routes and webhook placeholder
- \`teleforge.app.json\`: App manifest

## Modes

- \`/\`: available in inline, compact, and fullscreen launch modes
- \`/settings\`: fullscreen-only sample route with additional guard requirements
`;
}

function generatedRootPackageJson(options: BuildProjectFilesOptions): string {
  return stringifyJson({
    name: options.appId,
    private: true,
    version: "1.0.0",
    workspaces: ["apps/*"],
    scripts: {
      dev: "teleforge dev",
      "dev:https": "teleforge dev:https",
      doctor: "teleforge doctor"
    },
    dependencies: teleforgeDependencies,
    devDependencies: {
      "@teleforge/devtools": "^1.0.0",
      tsx: "^4.19.2",
      typescript: "^5.8.3"
    }
  });
}

function generatedManifest(options: BuildProjectFilesOptions): string {
  const runtime =
    options.mode === "spa"
      ? {
          mode: "spa",
          webFramework: "vite",
          build: {
            outDir: "dist",
            basePath: "/"
          }
        }
      : {
          mode: "bff",
          webFramework: "nextjs",
          apiRoutes: "apps/api/src/routes"
        };

  return stringifyJson({
    $schema: "https://teleforge.dev/schemas/app-manifest.json",
    id: options.appId,
    name: options.appName,
    version: "1.0.0",
    runtime,
    bot: {
      username: options.botUsername,
      tokenEnv: "BOT_TOKEN",
      webhook: {
        path: "/api/webhook",
        secretEnv: "WEBHOOK_SECRET"
      },
      commands: [
        {
          command: "start",
          description: "Start the Mini App",
          handler: "commands/start"
        }
      ]
    },
    miniApp: {
      entryPoint: "apps/web/src/main.tsx",
      launchModes: ["inline", "compact", "fullscreen"],
      defaultMode: "inline",
      capabilities: ["write_access", "read_access"]
    },
    routes: [
      {
        path: "/",
        component: "pages/Home",
        launchModes: ["inline", "compact", "fullscreen"],
        guards: ["auth"]
      },
      {
        path: "/settings",
        component: "pages/Settings",
        launchModes: ["fullscreen"],
        guards: ["auth", "write_access"]
      }
    ],
    permissions: [
      {
        capability: "write_access",
        description: "Post messages on user's behalf"
      }
    ]
  });
}

function generatedBaseTsconfig(): string {
  return stringifyJson({
    compilerOptions: {
      target: "ES2022",
      strict: true,
      noEmit: true,
      jsx: "react-jsx",
      esModuleInterop: true,
      forceConsistentCasingInFileNames: true,
      skipLibCheck: true
    }
  });
}

function generatedGitignore(): string {
  return `node_modules
dist
.next
.env
.env.local
`;
}

function envExample(): string {
  return `# Bot Configuration
BOT_TOKEN=your_bot_token_here
WEBHOOK_SECRET=your_webhook_secret_here

# Mini App Configuration
TELEGRAM_BOT_USERNAME=your_bot_username

# Optional: Development
TELEFORGE_DEV_PORT=3000
TELEFORGE_DEV_HTTPS=true
`;
}

function generatedApiPackageJson(): string {
  return stringifyJson({
    name: "@app/api",
    private: true,
    version: "1.0.0",
    type: "module",
    scripts: {
      dev: "tsx watch src/index.ts"
    }
  });
}

function apiTsconfig(): string {
  return stringifyJson({
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      module: "NodeNext",
      moduleResolution: "NodeNext",
      allowImportingTsExtensions: true
    },
    include: ["src/**/*.ts"]
  });
}

function apiIndexTs(): string {
  return `import { healthRoute } from "./routes/health.ts";
import { webhookRoute } from "./routes/webhook.ts";

export const apiRoutes = [healthRoute, webhookRoute];

export function createApiServer() {
  return {
    routes: apiRoutes,
    description: "Wire these routes into the Teleforge BFF or local dev runtime."
  };
}
`;
}

function apiHealthRouteTs(): string {
  return `export const healthRoute = {
  method: "GET",
  path: "/api/health",
  handler() {
    return {
      ok: true,
      timestamp: new Date().toISOString()
    };
  }
};
`;
}

function apiWebhookRouteTs(): string {
  return `export const webhookRoute = {
  method: "POST",
  path: "/api/webhook",
  handler(payload: unknown) {
    return {
      ok: true,
      received: payload
    };
  }
};
`;
}

function generatedBotPackageJson(): string {
  return stringifyJson({
    name: "@app/bot",
    private: true,
    version: "1.0.0",
    type: "module",
    scripts: {
      dev: "tsx watch src/index.ts"
    }
  });
}

function botTsconfig(): string {
  return stringifyJson({
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      module: "NodeNext",
      moduleResolution: "NodeNext",
      allowImportingTsExtensions: true
    },
    include: ["src/**/*.ts"]
  });
}

function botIndexTs(): string {
  return `import { startCommand } from "./commands/start.ts";

export const commands = [startCommand];

export function createBot() {
  return {
    commands,
    description: "Register these handlers with @teleforge/bot."
  };
}
`;
}

function botStartCommandTs(appName: string): string {
  return `export const startCommand = {
  command: "start",
  description: "Start the Mini App",
  async handler() {
    return {
      text: "Welcome to ${appName}. Launch the Mini App to continue."
    };
  }
};
`;
}

function generatedWebFiles(options: BuildProjectFilesOptions): Record<string, string> {
  return options.mode === "spa" ? spaWebFiles(options) : bffWebFiles(options);
}

function spaWebFiles(options: BuildProjectFilesOptions): Record<string, string> {
  return {
    "apps/web/index.html": spaIndexHtml(options.appName),
    "apps/web/package.json": stringifyJson({
      name: "@app/web",
      private: true,
      version: "1.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview"
      },
      dependencies: {
        react: "^18.3.1",
        "react-dom": "^18.3.1"
      },
      devDependencies: {
        "@types/react": "^18.3.12",
        "@types/react-dom": "^18.3.1",
        "@vitejs/plugin-react": "^4.3.1",
        vite: "^5.4.10"
      }
    }),
    "apps/web/src/App.tsx": spaAppTsx(options.appName),
    "apps/web/src/guards/launchMode.ts": launchModeGuardTs(),
    "apps/web/src/main.tsx": spaMainTsx(),
    "apps/web/src/pages/Home.tsx": homePageTsx(options.appName),
    "apps/web/src/pages/Settings.tsx": settingsPageTsx(),
    "apps/web/src/styles.css": webStylesCss(),
    "apps/web/tsconfig.json": stringifyJson({
      extends: "../../tsconfig.base.json",
      compilerOptions: {
        module: "ESNext",
        moduleResolution: "Bundler"
      },
      include: ["src/**/*.ts", "src/**/*.tsx"]
    }),
    "apps/web/vite.config.ts": viteConfigTs()
  };
}

function bffWebFiles(options: BuildProjectFilesOptions): Record<string, string> {
  return {
    "apps/web/app/globals.css": webStylesCss(),
    "apps/web/app/layout.tsx": nextLayoutTsx(options.appName),
    "apps/web/app/page.tsx": nextPageTsx("Home", "../src/pages/Home"),
    "apps/web/app/settings/page.tsx": nextPageTsx("Settings", "../../src/pages/Settings"),
    "apps/web/next-env.d.ts": `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n`,
    "apps/web/next.config.mjs": `const nextConfig = {};\n\nexport default nextConfig;\n`,
    "apps/web/package.json": stringifyJson({
      name: "@app/web",
      private: true,
      version: "1.0.0",
      type: "module",
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start"
      },
      dependencies: {
        next: "^14.2.15",
        react: "^18.3.1",
        "react-dom": "^18.3.1"
      },
      devDependencies: {
        "@types/react": "^18.3.12",
        "@types/react-dom": "^18.3.1"
      }
    }),
    "apps/web/src/guards/launchMode.ts": launchModeGuardTs(),
    "apps/web/src/main.tsx": nextEntryPointTs(),
    "apps/web/src/pages/Home.tsx": homePageTsx(options.appName),
    "apps/web/src/pages/Settings.tsx": settingsPageTsx(),
    "apps/web/tsconfig.json": stringifyJson({
      extends: "../../tsconfig.base.json",
      compilerOptions: {
        jsx: "preserve",
        allowJs: false,
        incremental: true,
        module: "ESNext",
        moduleResolution: "Bundler",
        isolatedModules: true,
        plugins: [{ name: "next" }]
      },
      include: ["next-env.d.ts", "app/**/*.ts", "app/**/*.tsx", "src/**/*.ts", "src/**/*.tsx"]
    })
  };
}

function spaIndexHtml(appName: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function viteConfigTs(): string {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()]
});
`;
}

function spaMainTsx(): string {
  return `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./styles.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;
}

function spaAppTsx(appName: string): string {
  return `import { useEffect, useState } from "react";
import { HomePage } from "./pages/Home";
import { SettingsPage } from "./pages/Settings";

function resolveRoute(pathname: string) {
  return pathname === "/settings" ? "settings" : "home";
}

export default function App() {
  const [route, setRoute] = useState(() => resolveRoute(window.location.pathname));

  useEffect(() => {
    const handlePopState = () => setRoute(resolveRoute(window.location.pathname));
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, []);

  const navigate = (pathname: string) => {
    window.history.pushState({}, "", pathname);
    setRoute(resolveRoute(pathname));
  };

  return (
    <main className="shell">
      <header className="hero">
        <p className="eyebrow">Teleforge Starter</p>
        <h1>${appName}</h1>
        <p className="lede">
          Generated with the SPA scaffold. The sample routes mirror the manifest launch-mode rules.
        </p>
        <nav className="nav">
          <button type="button" onClick={() => navigate("/")}>
            Home
          </button>
          <button type="button" onClick={() => navigate("/settings")}>
            Settings
          </button>
        </nav>
      </header>
      <section className="card">{route === "settings" ? <SettingsPage /> : <HomePage />}</section>
    </main>
  );
}
`;
}

function nextLayoutTsx(appName: string): string {
  return `import "./globals.css";
import type { ReactNode } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="shell">
          <header className="hero">
            <p className="eyebrow">Teleforge Starter</p>
            <h1>${appName}</h1>
            <p className="lede">
              Generated with the BFF scaffold. Sample routes mirror the manifest launch-mode rules.
            </p>
            <nav className="nav">
              <a href="/">Home</a>
              <a href="/settings">Settings</a>
            </nav>
          </header>
          <section className="card">{children}</section>
        </main>
      </body>
    </html>
  );
}
`;
}

function nextPageTsx(pageName: "Home" | "Settings", importPath: string): string {
  return `"use client";

import { ${pageName}Page } from "${importPath}";

export default function Page() {
  return <${pageName}Page />;
}
`;
}

function nextEntryPointTs(): string {
  return `export { HomePage } from "./pages/Home";
export { SettingsPage } from "./pages/Settings";
`;
}

function homePageTsx(appName: string): string {
  return `import { requireLaunchMode } from "../guards/launchMode";

export function HomePage() {
  requireLaunchMode(["inline", "compact"]);

  return (
    <div className="stack">
      <p className="badge">Route: /</p>
      <h2>Welcome to ${appName}</h2>
      <p>
        This sample page is available in inline and compact launch modes and demonstrates an auth guard.
      </p>
    </div>
  );
}
`;
}

function settingsPageTsx(): string {
  return `import { requireLaunchMode } from "../guards/launchMode";

export function SettingsPage() {
  requireLaunchMode(["fullscreen"]);

  return (
    <div className="stack">
      <p className="badge">Route: /settings</p>
      <h2>Settings</h2>
      <p>
        This page is restricted to fullscreen mode and maps to the manifest's stronger capability requirements.
      </p>
    </div>
  );
}
`;
}

function launchModeGuardTs(): string {
  return `import { useLaunch } from "@teleforge/web";

export function requireLaunchMode(allowedModes: string[]) {
  const { mode } = useLaunch();

  if (!allowedModes.includes(mode)) {
    throw new Error(\`Route requires launch mode: \${allowedModes.join(", ")}\`);
  }

  return true;
}
`;
}

function webStylesCss(): string {
  return `:root {
  color-scheme: light;
  font-family: "IBM Plex Sans", sans-serif;
  background:
    radial-gradient(circle at top left, rgba(76, 175, 80, 0.18), transparent 32%),
    radial-gradient(circle at top right, rgba(33, 150, 243, 0.14), transparent 28%),
    #f5f7fb;
  color: #18212f;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
}

a,
button {
  border: 0;
  background: #18212f;
  color: #ffffff;
  border-radius: 999px;
  padding: 0.7rem 1rem;
  cursor: pointer;
  font: inherit;
  text-decoration: none;
}

.shell {
  width: min(960px, calc(100% - 2rem));
  margin: 0 auto;
  padding: 3rem 0 4rem;
}

.hero {
  display: grid;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.hero h1,
.card h2 {
  margin: 0;
}

.eyebrow,
.badge {
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-size: 0.85rem;
  color: #4f5d75;
}

.lede {
  max-width: 48rem;
  line-height: 1.6;
}

.nav {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
}

.card {
  background: rgba(255, 255, 255, 0.88);
  backdrop-filter: blur(14px);
  border: 1px solid rgba(24, 33, 47, 0.08);
  border-radius: 24px;
  padding: 1.5rem;
  box-shadow: 0 20px 60px rgba(24, 33, 47, 0.08);
}

.stack {
  display: grid;
  gap: 0.75rem;
}
`;
}

function stringifyJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}
