import { BffErrorCodes } from "./codes.js";

import type { BffErrorCode } from "./codes.js";

const STATUS_BY_CODE: Record<BffErrorCode, number> = {
  DUPLICATE_HANDLER: 500,
  DUPLICATE_ROUTE: 500,
  IDENTITY_RESOLUTION_FAILED: 401,
  IDENTITY_STRATEGY_INVALID: 500,
  INTERNAL_ERROR: 500,
  INVALID_INIT_DATA: 401,
  LAUNCH_MODE_NOT_ALLOWED: 403,
  MALFORMED_BODY: 400,
  MIDDLEWARE_ERROR: 500,
  MISSING_BOT_ID: 400,
  MISSING_HANDLER: 500,
  MISSING_REQUIRED_BODY: 400,
  MISSING_VALIDATION_CREDENTIALS: 400,
  REFRESH_TOKEN_INVALID: 401,
  RUNTIME_UNSUPPORTED: 500,
  RUNTIME_UNSUPPORTED_VALIDATION: 500,
  SESSION_REVOKED: 401,
  TIMEOUT: 504,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  UNAUTHENTICATED: 401
};

export function getStatusCodeForBffError(code: BffErrorCode): number {
  return STATUS_BY_CODE[code] ?? STATUS_BY_CODE[BffErrorCodes.INTERNAL_ERROR];
}
